Add/no acr
meateam/drive-project pull request #137
Opened 2021-04-26 07:13 UTC by yosef32

Gives the option to run the script with the choice to use ACR or not.
Login to ACR by username and password entered in environment variables (deploy.env)

2021-04-26 08:41 UTC, Shahar-Y requested changes
How can you pull the images without registering to the repositoy?

2021-04-29 07:06 UTC, nettashviro requested changes

2021-04-29 07:06 UTC, nettashviro commented on deployment.sh
> +    docker login  drivehub.azurecr.io -u $ACR_USER -p $ACR_PASS
i'll prefer using "az login", the credentials stays for 3 days and you only need to call az acr login. why are you using this command?

2021-04-29 07:06 UTC, nettashviro commented on deployment.sh
> +    docker login  drivehub.azurecr.io -u $ACR_USER -p $ACR_PASS
and also use env variables (AZURE_LOGIN_SERVER)

2021-05-02 10:22 UTC, yosef32 commented on deployment.sh
> +    docker login  drivehub.azurecr.io -u $ACR_USER -p $ACR_PASS
It does not need a person for this operation, for az login volume that needs to be confirmed by user clicks

2021-05-02 10:23 UTC, yosef32 commented on deployment.sh
> +    docker login  drivehub.azurecr.io -u $ACR_USER -p $ACR_PASS
this user and pass is specific to the acr

2021-05-02 10:25 UTC, yosef32 commented on README.md
> +ACR_USER="DriveHub"             # acr username from drivehub Access keys in azure
done

2021-05-04 16:04 UTC, Shahar-Y approved these changes
Good job, make sure it is pushed to master accordingly

2021-05-05 05:46 UTC, nettashviro requested changes

2021-05-05 05:46 UTC, nettashviro commented on services.dev.json
> +        "tag": "upload_folder"
in develop json it should always stays in develop tag. if you want to change the json to your local environment you should use services.local.json

2021-05-05 05:46 UTC, nettashviro commented on z-helm/drive-ui/values.yaml
> +  tag: "upload_folder"
same as my previous comment

2021-05-05 05:47 UTC, nettashviro commented on deployment.sh
> +    docker login  drivehub.azurecr.io -u $ACR_USER -p $ACR_PASS
the server url is the same for every user

2021-05-19 11:38 UTC, merged