Feature/add script for tagging
meateam/drive-project pull request #82
Opened 2020-09-21 09:36 UTC by nettashviro

2020-09-22 06:39 UTC, Shahar-Y requested changes
Excellent documentation. 
I have some comments about your failure-handling, but other than that - great job :+1:

2020-09-22 06:39 UTC, Shahar-Y commented on deployment.prod.sh
> +        echo "Git tag $2 doesnt exists for repo $1"
```suggestion
        echo "Git tag $2 doesnt exist for repo $1"
```

2020-09-22 06:39 UTC, Shahar-Y commented on deployment.prod.sh
> +        exit
The script exits after some of the repositories may have been changed. 
I think it would be better to run the check first  - and only then change and push the repositories and their images

2020-09-22 06:39 UTC, Shahar-Y commented on deployment.prod.sh
> +helm_change_tag() {
What if it failed to find the regex?
Should the user be notified in case of failure or should the whole script exit?

2020-09-22 06:39 UTC, Shahar-Y commented on deployment.prod.sh
> +        docker pull $AZURE_LOGIN_SERVER/$1:$2
Again, what if a single service fails?

2020-09-22 06:39 UTC, Shahar-Y commented on services.prod.json
> +]
newline

2020-09-22 07:01 UTC, nettashviro commented on deployment.prod.sh
> +JSON_FILE="services.prod.json"                                                  # Insert name of the json services file
It's not critical, it's only the file's name. I named this file like that because of farther thought that we would want to implement several environments like - develop and for production.

2020-09-22 07:02 UTC, nettashviro commented on deployment.prod.sh
> +JSON_FILE="services.prod.json"                                                  # Insert name of the json services file
The meaning is that the file contains tags that are production-ready

2020-09-22 07:04 UTC, nettashviro commented on services.prod.json
> +]
I told you, when I save the file the newline is deleted.

2020-09-22 07:06 UTC, nettashviro commented on deployment.prod.sh
> +        echo "Git tag $2 doesnt exists for repo $1"
DONE

2020-09-23 08:14 UTC, nettashviro commented on deployment.prod.sh
> +if [ "$1" == "--zip" ] || [ "$2" == "--zip" ]; then
Modified the flag implementation, without the method you suggested because it's more fitted in cases of scripts with flags and values, In this script I used flags without values.  
https://unix.stackexchange.com/questions/507763/script-with-more-than-one-flag

2020-09-23 08:16 UTC, nettashviro commented on deployment.prod.sh
> +        exit
Added another for loop that check if the tags exist in git before doing any changes.

2020-09-23 09:01 UTC, nettashviro commented on deployment.prod.sh
> +helm_change_tag() {
I added a test to see if the "tag" attribute exists in values.yml file. if the script can't find the test attribute, the user would be notified, the script won't fail.

2020-09-23 09:14 UTC, nettashviro commented on deployment.prod.sh
> +        docker pull $AZURE_LOGIN_SERVER/$1:$2
There is no consistent status code for docker pull. The operation itself prints the process and shows if the docker pull was successful. The only thing that does not happen is that the script will not perform an exit action in case of failure.

2020-09-24 07:27 UTC, Shahar-Y approved these changes

2020-09-29 07:49 UTC, merged